USE NutritionBuddy;

-- Client sample data (35 rows)
INSERT INTO Client (Name, DOB, Email) VALUES
('James Wilson', '1985-03-12', 'jwilson85@gmail.com'),
('Emma Garcia', '1990-07-25', 'emma.garcia@outlook.com'),
('Michael Johnson', '1978-11-08', 'mjohnson78@yahoo.com'),
('Sophia Martinez', '1992-04-17', 'smartinez92@gmail.com'),
('William Anderson', '1983-09-30', 'will.anderson@hotmail.com'),
('Olivia Thompson', '1995-02-15', 'olivia_t@icloud.com'),
('Noah Chen', '1975-06-22', 'noah.chen75@gmail.com'),
('Ava Rodriguez', '1988-12-05', 'avarodriguez@yahoo.com'),
('Liam Hernandez', '1991-08-19', 'liam.h91@gmail.com'),
('Charlotte Lewis', '1980-01-29', 'charlotte.lewis80@outlook.com'),
('Benjamin Walker', '1993-05-14', 'benwalker@gmail.com'),
('Amelia Singh', '1986-10-27', 'amelia.singh@yahoo.com'),
('Elijah Patel', '1979-07-11', 'e.patel79@gmail.com'),
('Mia Young', '1994-03-24', 'miayoung94@outlook.com'),
('Jamal Washington', '1982-12-08', 'jwashington@gmail.com'),
('Aisha Khan', '1989-09-16', 'aisha.khan89@yahoo.com'),
('Mason Scott', '1977-04-30', 'mason.scott@hotmail.com'),
('Zoe Greene', '1996-01-13', 'zoegreene96@gmail.com'),
('Logan Baker', '1984-08-26', 'logan_baker@outlook.com'),
('Abigail Adams', '1991-05-09', 'abby.adams@icloud.com'),
('Jackson Nelson', '1976-11-22', 'jnelson76@gmail.com'),
('Maria Gonzalez', '1987-02-06', 'mariag@yahoo.com'),
('Tyrone Roberts', '1993-07-19', 'tyrone93@gmail.com'),
('Sofia Nguyen', '1980-04-02', 's.nguyen@outlook.com'),
('Grayson Phillips', '1990-10-15', 'gphillips90@gmail.com'),
('Aaliyah Evans', '1983-06-28', 'aaliyah.e@yahoo.com'),
('Hiroshi Tanaka', '1979-01-11', 'h.tanaka@gmail.com'),
('Riley Diaz', '1995-11-24', 'riley.diaz@hotmail.com'),
('Julian Kim', '1981-08-07', 'juliankim@gmail.com'),
('Lily Zhang', '1994-03-21', 'lilyzhang94@outlook.com'),
('Isaiah Reed', '1986-09-04', 'isaiah.reed86@yahoo.com'),
('Fatima Hassan', '1988-12-17', 'fatima.h@gmail.com'),
('David Kelly', '1982-05-30', 'davidk82@hotmail.com'),
('Zainab Ahmed', '1997-02-13', 'zainab.a@gmail.com'),
('Eli Cox', '1984-07-26', 'eli.cox84@outlook.com');

-- Nutritionist sample data (35 rows)
INSERT INTO Nutritionist (Name, Email) VALUES
('Dr. Sarah Johnson, RD', 'sjohnson@nutritionbuddy.com'),
('Robert Smith, MS, CNS', 'robert.smith@nutritionbuddy.com'),
('Alexandra Williams, RDN', 'alex.williams@nutritionbuddy.com'),
('Thomas Brown, PhD', 'thomas.brown@nutritionbuddy.com'),
('Dr. Emily Davis, RD, CDE', 'emily.davis@nutritionbuddy.com'),
('Daniel Miller, MS, RD', 'daniel.miller@nutritionbuddy.com'),
('Sophia Wilson, CNS', 'sophia.wilson@nutritionbuddy.com'),
('Dr. David Moore, MD, FACN', 'david.moore@nutritionbuddy.com'),
('Olivia Taylor, RDN, LD', 'olivia.taylor@nutritionbuddy.com'),
('Dr. Matthew Anderson, PhD', 'matthew.anderson@nutritionbuddy.com'),
('Emma Thomas, MS, RD', 'emma.thomas@nutritionbuddy.com'),
('Christopher Jackson, RD, CSSD', 'christopher.jackson@nutritionbuddy.com'),
('Isabella White, RDN, LDN', 'isabella.white@nutritionbuddy.com'),
('Dr. Andrew Harris, MD', 'andrew.harris@nutritionbuddy.com'),
('Ava Martin, MS, CNS', 'ava.martin@nutritionbuddy.com'),
('Dr. Joseph Thompson, PhD', 'joseph.thompson@nutritionbuddy.com'),
('Mia Garcia, RDN, CDE', 'mia.garcia@nutritionbuddy.com'),
('Dr. Ryan Martinez, MD, MPH', 'ryan.martinez@nutritionbuddy.com'),
('Charlotte Robinson, MS, RD', 'charlotte.robinson@nutritionbuddy.com'),
('Dr. Nicholas Clark, PhD, RD', 'nicholas.clark@nutritionbuddy.com'),
('Amelia Rodriguez, RDN, CSOWM', 'amelia.rodriguez@nutritionbuddy.com'),
('Dr. Brandon Lewis, MD', 'brandon.lewis@nutritionbuddy.com'),
('Elizabeth Lee, MS, CNS', 'elizabeth.lee@nutritionbuddy.com'),
('Dr. Jonathan Walker, PhD', 'jonathan.walker@nutritionbuddy.com'),
('Harper Allen, RDN, CLT', 'harper.allen@nutritionbuddy.com'),
('Dr. Kevin Young, MD, RD', 'kevin.young@nutritionbuddy.com'),
('Abigail King, MS, RDN', 'abigail.king@nutritionbuddy.com'),
('Dr. Jason Wright, PhD', 'jason.wright@nutritionbuddy.com'),
('Ella Hill, RD, CSSD', 'ella.hill@nutritionbuddy.com'),
('Dr. Justin Scott, MD, FACN', 'justin.scott@nutritionbuddy.com'),
('Sofia Green, MS, RDN', 'sofia.green@nutritionbuddy.com'),
('Dr. Brian Baker, PhD, CNS', 'brian.baker@nutritionbuddy.com'),
('Layla Adams, RDN, LDN', 'layla.adams@nutritionbuddy.com'),
('Dr. Steven Nelson, MD', 'steven.nelson@nutritionbuddy.com'),
('Zoe Carter, MS, RD', 'zoe.carter@nutritionbuddy.com'); 